# Generated by Django 2.1.5 on 2019-03-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
