# Generated by Django 2.1.5 on 2019-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0003_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': '代码', 'verbose_name_plural': '代码'},
        ),
    ]
