<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0004_auto_20190302_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': [], 'verbose_name': '代码', 'verbose_name_plural': '代码'},
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-02 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0004_auto_20190302_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': [], 'verbose_name': '代码', 'verbose_name_plural': '代码'},
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
