<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0005_auto_20190302_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_itself',
            field=models.TextField(null=True),
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0005_auto_20190302_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_itself',
            field=models.TextField(null=True),
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
