# Generated by Django 2.1.5 on 2019-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0006_auto_20190302_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_id',
            field=models.IntegerField(default=0),
        ),
    ]
