<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0007_code_code_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['-code_id'], 'verbose_name': '代码', 'verbose_name_plural': '代码'},
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0007_code_code_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['-code_id'], 'verbose_name': '代码', 'verbose_name_plural': '代码'},
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
