# Generated by Django 2.1.5 on 2019-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0008_auto_20190302_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
