<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0009_code_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OJ用户',
                'verbose_name_plural': 'OJ用户',
                'ordering': ['-register_date'],
            },
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0009_code_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OJ用户',
                'verbose_name_plural': 'OJ用户',
                'ordering': ['-register_date'],
            },
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
