<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
