<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0011_user_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('is_private', models.BooleanField(default=False)),
                ('problems', models.ManyToManyField(to='judger.Problem')),
            ],
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0011_user_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('is_private', models.BooleanField(default=False)),
                ('problems', models.ManyToManyField(to='judger.Problem')),
            ],
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
