<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0012_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='duration',
            new_name='end_time',
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0012_contest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='duration',
            new_name='end_time',
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
