# Generated by Django 2.1.5 on 2019-03-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0013_auto_20190311_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
