# Generated by Django 2.1.5 on 2019-03-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0014_contest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='postman',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='judger.User'),
        ),
    ]
