<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0017_code_submit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-contest_id'], 'verbose_name': '比赛', 'verbose_name_plural': '比赛'},
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0017_code_submit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-contest_id'], 'verbose_name': '比赛', 'verbose_name_plural': '比赛'},
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
