# Generated by Django 2.1.5 on 2019-03-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0018_auto_20190315_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('board', models.TextField()),
            ],
            options={
                'verbose_name': '可编辑',
                'verbose_name_plural': '可编辑',
            },
        ),
    ]
