# Generated by Django 2.1.5 on 2019-03-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0019_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
