<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0020_problem_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted',
            field=models.ManyToManyField(to='judger.Problem'),
        ),
    ]
=======
# Generated by Django 2.1.5 on 2019-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0020_problem_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted',
            field=models.ManyToManyField(to='judger.Problem'),
        ),
    ]
>>>>>>> 925150b4b2604b4b2f453c3826270df15953848c
