# Generated by Django 2.1.5 on 2019-03-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0021_user_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ac_count',
            field=models.IntegerField(default=0),
        ),
    ]
