# Generated by Django 2.1.5 on 2019-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0023_auto_20190325_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accepted',
            field=models.ManyToManyField(to='judger.Problem'),
        ),
    ]
