# Generated by Django 2.2 on 2019-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0024_auto_20190325_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contestant',
            field=models.ManyToManyField(to='judger.User'),
        ),
    ]
