# Generated by Django 2.2 on 2019-07-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger', '0025_contest_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='OLE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='PE',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='RF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='SE',
            field=models.BooleanField(default=False),
        ),
    ]
